import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

import styles from "../styles/Home.module.css"



export default function Home() {
  return (
    <>
      <Head>
        <title>petthepotat - Home</title>
        <meta name="description" content="Generated by create next app" />        
      </Head>

    <div className={styles.Body}>

      {/* nav */}
      <nav className={styles.NavContainer}>
        <div className={styles.NavBarBackground}></div>
        <div className={styles.NavBar}>
          <Link href="#" className={styles.NavBarIcon}>
            <Image alt='navbaricon' src='/favicon.ico' className={styles.NavBarLogo} width='100' height='100'/>
            <div className={`${styles.NavBarText} ${styles.NavBarLogoText}`}>petthepotat</div>
          </Link>
          <span></span>
          <div className={styles.NavBarButton}><Link href="#">Home</Link></div>
          <div className={styles.NavBarButton}><Link href="#">About</Link></div>
          <div className={styles.NavBarButton}><Link href="#">Projects</Link></div>
          <div className={styles.NavBarButton}><Link href="#">Contact</Link></div>
        </div>
      </nav>

      <main style={{position: `absolute`, width: `100%`, left: `0px`, zIndex: 1, background: `black`}}>

        {/* hero */}
        <div className={styles.Hero}>
          <div className={`${styles.HeroBackContainer}}`}>
            <Image src='/banner.png' alt='background image' width='1280' height='720' className={styles.HeroBackground}/>
          </div>
          <div className={styles.HeroSpacing}></div>
          <div className={styles.HeroText}>
            <div className={styles.HeroTitle}>petthepotat</div>
            <div className={styles.HeroSubtitle}>I'm a software developer</div>
          </div>
        </div>

        {/* github */}
        <div className={`${styles.Github} ${styles.ContentContainer}`}>
          <div className={styles.GithubTitle}>
            Github
            <div className={styles.HeroIcon}>
              <Image alt="github" src='https://cdn-icons-png.flaticon.com/512/3291/3291695.png' 
                  width='100' height='100' className={styles.HeroIconImage}/>
            </div>
          </div>
          <div className={styles.GithubSubtitle}>Here are some projects!</div>
          <div className={styles.GithubContentContainer}>
            <div className={styles.ContentCard}>
              <Image src='/git-portfolio.jpg' alt='portfolio website' 
                  width='720' height='360'/>
              <h1>portfolio</h1>
              <h2>this website!</h2>
            </div>
            <div className={styles.ContentCard}>
              <Image src='/git-glfw-engine.png' alt='glfw engine' 
                  width='720' height='360'/>
              <h1>OpenGL & C++</h1>
              <h2>opengl rendering with c++</h2>
            </div>
            <div className={styles.ContentCard}>
              <Image src='/git-rpg-prototype.png' alt='rpg' 
                  width='720' height='360'/>
              <h1>RPG Prototype</h1>
              <h2>i like rpg games</h2>
            </div>
          </div>
        </div>

        {/* side by side container */}
        <div className={styles.Side2ContentContainer}>
          {/* random spotify blob */}
          <div className={styles.Side2ContentSection}>
            <div className={`${styles.Spotify} ${styles.ContentContainer}`}>
              <div className={styles.SpotifyTitle}>Spotify</div>
              <div className={styles.SpotifySubtitle}>Here's what I'm listening to!</div>
              <iframe src="https://open.spotify.com/embed/playlist/1UAQ7WYIxbptNETMqbemLQ?utm_source=generator" 
                    className={styles.SpotifyFrame} allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
            </div>
          </div>

          {/* kofi */}
          <div className={`${styles.Kofi} ${styles.ContentContainer}`}>
            <div className={styles.KofiTitle}>Kofi</div>
            <div className={styles.KofiSubtitle}>Here's my kofi!</div>
            {/*  random kofi thing -- plz check  */}
            <script type='text/javascript' src='https://storage.ko-fi.com/cdn/widget/Widget_2.js'></script>
            <script type='text/javascript'>kofiwidget2.init('Support Me on Ko-fi', '#29abe0', 'W7W8DGZ7W');kofiwidget2.draw();</script> 
            <iframe id='kofiframe' src='https://ko-fi.com/petthepotat/?hidefeed=true&widget=true&embed=true&preview=true' 
                className={styles.KofiFrame} title='petthepotat'></iframe>
          </div>
        </div>

        {/* About me */}
        <div className={`${styles.About} ${styles.ContentContainer}`}>
          <div className={styles.AboutTitle}>About Me</div>
          <div className={styles.AboutSubtitle}>Here's some stuff about me!</div>
          <div className={styles.AboutContainer}>
            <div className={styles.AboutSubContainer}>
              <Image src='/git-glfw-engine.png' alt='glfw engine' 
                  width='720' height='100' className={styles.ContentImage}/>
              <div className={styles.AboutCard}>
                hawdw
              </div>
            </div>
            <div className={styles.AboutSubContainer}>
              <Image src='/git-glfw-engine.png' alt='glfw engine' 
                  width='720' height='100' className={styles.ContentImage}/>
              subcontainer
            </div>
          </div>
        </div>

        {/* Contact */}
        <div className={`${styles.Contact} ${styles.ContentContainer}`}>
          <div className={styles.ContactTitle}>Contact</div>
          <div className={styles.ContactSubtitle}>Here's how to contact me!</div>

          <div className={styles.ContactContainer}>
            <div className={styles.ContactEmailSender}>
              <div className={styles.ContactEmailSenderTitle}>Email</div>
              <div className={styles.ContactEmailSenderSubtitle}>Send me an email!</div>
              <div className={styles.ContactEmailSenderInputContainer}>
                <input className={styles.ContactEmailSenderInput} placeholder="Email"></input>
                <input className={styles.ContactEmailSenderInput} placeholder="Subject"></input>
                <textarea className={styles.ContactEmailSenderInput} placeholder="Message"></textarea>
                <button className={styles.ContactEmailSenderButton}>Send</button>
              </div>
            </div>
          </div>
        </div>

      </main>
    </div>
    </>
  )
}
